version: "3.1"
services:
  #mysql:
  #  image: mysql:5.7
  #  ports:
  #    - "3306:3306"
  #  command: --default-authentication-plugin=mysql_native_password
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #  networks:
  #    - babynet
  web:
    # replace username/repo:tag with your name and image details
    image: babynamer:latest
    deploy:
      replicas: 1
    environment:
      ROOT_PASSWORD: root
      DB_NAME: docker_baby
      DB_USERNAME: babyuser
      DB_HOST: "192.168.11.140"
      DB_PASSWORD: oogabooga
      BUILDTYPE: docker
      DOCKER: "yes"
      DAEMONIZE: "no"
    ports:
      - "4000:4000"
    networks:
      - babynet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - babynet
networks:
  babynet: